# Generated by Django 2.2.1 on 2019-06-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeplease', '0002_auto_20190604_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='countable',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='item',
            name='note',
            field=models.CharField(default='Note', max_length=100),
        ),
    ]
