# Generated by Django 2.2.1 on 2019-06-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeplease', '0003_auto_20190605_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='note',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
