# Generated by Django 2.2.1 on 2019-06-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeplease', '0005_auto_20190605_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card')], max_length=4),
        ),
    ]
